global:
  scrape_interval: 5s
  scrape_timeout: 3s
  evaluation_interval: 5s

# Our alerting rule files
#rule_files:
#- "alert.rules"

# Scrape endpoints
scrape_configs:
  #- job_name: 'prometheus'
  #static_configs:
  #- targets: ['localhost:9090']

  - job_name: "NMprod_DB"
    static_configs:
      - targets: ["192.0.2.0:9105"]

  - job_name: "docker"
    static_configs:
      - targets: ["192.0.2.0:9323"]

  - job_name: node_NM
    static_configs:
      - targets: ["192.0.2.0:9100"]

  - job_name: cadvisor_NM
    scrape_interval: 5s
    static_configs:
      - targets: ["192.0.2.0:9080"]

rule_files:
  - "mysql_exporter_recording_rules.yml"

remote_write:
  - url: http://192.0.2.0:9090
    basic_auth:
      username: exporter
      password: prompass
